openapi: 3.0.3
# checkov:skip=CKV_OPENAPI_4: TODO https://nhsd-jira.digital.nhs.uk/browse/DOSIS-1842
# checkov:skip=CKV_OPENAPI_21: TODO https://nhsd-jira.digital.nhs.uk/browse/DOSIS-1842
info:
  title: Directory of Services Ingestion API
  description: |
    ## Overview

    Use this API to submit service data from your system to the NHS [Directory of Services (DoS)](https://digital.nhs.uk/services/directory-of-services-dos). This API enables data providers to send structured updates: such as service availability, contact details, or referral information; which are validated and prepared for inclusion in the national DoS.

    Once submitted, the data will either undergo manual assurance by DoS leads or, in applicable cases, be processed through an automated assurance workflow. If manual assurance is required, the sender will receive an acknowledgment confirming that the data has been successfully submitted and is pending review.

    The API is designed for secure, system-to-system communication and supports consistent, efficient data submission; helping ensure the DoS remains accurate and up to date for use across NHS systems.

    ## Who can use this API

    This API is intended for approved data providers who need to submit or update service information in the NHS Directory of Services (DoS). Typical users may include NHS organizations, local authorities, or trusted third-party systems that manage health and care service data.

    To use this API, both your organization and the data source must be formally approved through our assurance process. This ensures that only high-quality, trusted data is submitted into the DoS.

    Before access is granted, your organization must:
    * contact our integration team to discuss your use case and technical approach
    * undergo a technical and data assurance process to validate the structure, accuracy, and governance of the data source you plan to use
    * receive approval that your system and data are fit for integration with the DoS Ingestion API

    Use of this API is subject to data governance requirements and must align with approved use cases.

    ## Access modes

    This API has two access modes. They are:
      * Application Restricted - Addition of new resource allowed / replacement of organization allowed
      * User Restricted - Healthcare worker access for authentication via a UI (User Interface)

    ## Roadmap
    We're currently finalising our roadmap and we'll update this content in due course.

    ## Service level

    TBC when service is in Beta.

    ## Technology

    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).

    It conforms to the FHIR UK Core STU3 v0.0.6, based on FHIR R4 v4.0.1.

    You do not need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules. In particular:
    * resource names are capitalised and singular, for example /Patient not /patients
    * array names are singular, for example line not lines for address lines
    * data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an extension object

    There are [libraries and SDKs available](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) to help with FHIR API integration.

    ## Network access

    This API is available on the Internet.

    ## Errors

    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:
    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.

    ## Open source

    You might find the following open source resources useful:
    | Resource | Description | Link |
    |-----|-----|-----|
    |Directory of Service Ingress API | Source code for the API proxy, sandbox and specification | [Github](https://github.com/NHSDigital/ftrs-directory-of-services) |
    | ETL Layer | ETL developed for Data Sourcing Partners | [Github](https://github.com/NHSDigital/ftrs-directory-of-services)|
    | FHIR libraries and SDKs | Various open source libraries for integrating with FHIR APIs | [FHIR libraries and SDKs](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) |

    ## Environments and testing

    TBC links to available environments:

    | Environment | Base URL |
    |-------------|----------|
    | Sandbox | https://sandbox.api.service.nhs.uk/dos-ingestion/FHIR/R4 |
    | Integration | https://int.api.service.nhs.uk/dos-ingestion/FHIR/R4 |
    | Production | https://api.service.nhs.uk/dos-ingestion/FHIR/R4 |

    ### Sandbox

    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is stateless, so does not actually persist any updates
    * is open access, so does not allow you to test authorisation - TBC

    For details of sandbox test scenarios, or to try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint.

    TBC - More details to be posted on integration, authentication, resources or test data available in all our environments during Beta phase.

    ## Onboarding

    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it's worth planning well ahead.

    As part of this process, you need to demonstrate your technical conformance to the requirements for this API.

    ## Related APIs

    The following APIs are related to this one:
    * [Directory of Services - Urgent and Emergency Care - REST API](https://digital.nhs.uk/developer/api-catalogue/directory-of-services-urgent-and-emergency-care-rest) - access information on a wide range of health and care services across England using our Directory of Services Urgent and Emergency Care
    * [Directory of Services - Urgent and Emergency Care - SOAP API](https://digital.nhs.uk/developer/api-catalogue/directory-of-services-soap) - use this API to access information on a wide range of health and care services across England
  version: 1.0.0
  contact:
    name: NHS Digital API Support
    url: https://digital.nhs.uk/developer/help-and-support
    email: api.management@nhs.net
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: 'https://internal-dev.api.service.nhs.uk/dos-ingestion/FHIR/R4'
    description: Development environment
security:
  - app-level0: []
paths:
  '/Organization/':
    post:
      summary: Create a new Organization
      description: Create a new Organization resource.
      security:
        - app-level0: []
      parameters:
      - in: header
        name: apiKey
        required: true
        description: |
          Use the unique api key provided to you during onboarding. This will be used to authorise API requests.
        schema:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
          example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
      - in: header
        name: X-Correlation-ID
        required: false
        description: |
          Use an optional ID to track transactions across multiple systems.
          Mirrored back in a response header.
        schema:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
          example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
      - in: header
        name: Content-Type
        required: true
        description: Content type must be application/fhir+json
        schema:
          type: string
          enum: ["application/fhir+json"]
          example: application/fhir+json
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/Organization'
            examples:
              organization_example:
                summary: Example Organization
                value:
                  resourceType: Organization
                  id: "00000000-0000-0000-0000-00000000000a"
                  meta:
                    profile: ["https://fhir.nhs.uk/StructureDefinition/UKCore-Organization"]
                  active: true
                  name: "GP Practice Name"
                  type:
                    - coding:
                        - system: "https://fhir.hl7.org.uk/CodeSystem/UKCore-OrganizationType"
                          code: "GP"
                          display: "GP Practice"
                  identifier:
                    - system: "https://fhir.nhs.uk/Id/ods-organization-code"
                      value: "ABC123"
                  telecom:
                    - system: phone
                      value: "01234 567890"
                      use: work
                  address:
                    - line: ["Example Medical Practice", "Example Street"]
                      city: "Example City"
                      postalCode: "AB12 3CD"
                      country: "ENGLAND"
      responses:
        '201':
          description: Organization created successfully
          headers:
            X-Correlation-ID:
              description: 'The X-Correlation-ID from the request header, if supplied, mirrored back.'
              schema:
                type: string
                example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
            Location:
              description: Location of the created resource
              schema:
                type: string
                example: "/Organization/00000000-0000-0000-0000-00000000000a"
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
            X-XSS-Protection:
              description: Enable XSS filtering
              schema:
                type: string
                example: "1; mode=block"
            Strict-Transport-Security:
              description: Enforce HTTPS
              schema:
                type: string
                example: "max-age=31536000; includeSubDomains"
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                created_organization:
                  summary: Created Organization Response
                  value:
                    resourceType: Organization
                    id: "00000000-0000-0000-0000-00000000000a"
                    meta:
                      profile: ["https://fhir.nhs.uk/StructureDefinition/UKCore-Organization"]
                      versionId: "1"
                      lastUpdated: "2024-01-15T10:30:00.000Z"
                    active: true
                    name: "GP Practice Name"
                    type:
                      - coding:
                          - system: "https://fhir.hl7.org.uk/CodeSystem/UKCore-OrganizationType"
                            code: "GP"
                            display: "GP Practice"
                    identifier:
                      - system: "https://fhir.nhs.uk/Id/ods-organization-code"
                        value: "ABC123"
                    telecom:
                      - system: phone
                        value: "01234 567890"
                        use: work
                    address:
                      - line: ["Example Medical Practice", "Example Street"]
                        city: "Example City"
                        postalCode: "AB12 3CD"
                        country: "ENGLAND"
        '400':
          description: Bad Request - Invalid input data
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              examples:
                validation_error:
                  summary: Validation Error
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: invalid
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/Codesystem/http-error-codes"
                              code: "VALIDATION_ERROR"
                        diagnostics: "Required field 'name' is missing"
        '401':
          description: Unauthorized - Invalid or missing API key
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              examples:
                unauthorized:
                  summary: Unauthorized Error
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: security
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/Codesystem/http-error-codes"
                              code: "UNAUTHORIZED"
                        diagnostics: "Invalid or missing API key"
        '403':
          description: Forbidden - Access denied
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '409':
          description: Conflict - Resource already exists
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '422':
          description: Unprocessable Entity - Semantic validation errors
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '429':
          description: Too Many Requests - Rate limit exceeded
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
            Retry-After:
              description: Number of seconds to wait before retrying
              schema:
                type: integer
                example: 60
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '500':
          description: Internal Server Error
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
  '/Organization/{id}':
    put:
      summary: Update/overwrite an Organization resource
      description: Update or overwrite an existing Organization resource by ID.
      security:
        - app-level0: []
      parameters:
      - in: header
        name: apiKey
        required: true
        description: |
          Use the unique api key provided to you during onboarding. This will be used to authorise API requests
        schema:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
          example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
      - in: header
        name: X-Correlation-ID
        required: false
        description: |
          Use an optional ID to track transactions across multiple systems.
          Mirrored back in a response header.
        schema:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
          example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
      - in: header
        name: Content-Type
        required: true
        description: Content type must be application/fhir+json
        schema:
          type: string
          enum: ["application/fhir+json"]
          example: application/fhir+json
      - in: path
        name: id
        description: The unique identifier of the Organization resource to update.
        required: true
        schema:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
          example: "00000000-0000-0000-0000-00000000000a"
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/Organization'
            examples:
              organization_update:
                summary: Organization Update Example
                value:
                  resourceType: Organization
                  id: "00000000-0000-0000-0000-00000000000a"
                  meta:
                    profile: ["https://fhir.nhs.uk/StructureDefinition/UKCore-Organization"]
                  active: true
                  name: "Updated GP Practice Name"
                  type:
                    - coding:
                        - system: "https://fhir.hl7.org.uk/CodeSystem/UKCore-OrganizationType"
                          code: "GP"
                          display: "GP Practice"
                  identifier:
                    - system: "https://fhir.nhs.uk/Id/ods-organization-code"
                      value: "ABC123"
                  telecom:
                    - system: phone
                      value: "01234 567890"
                      use: work
                  address:
                    - line: ["Updated Medical Practice", "Updated Street"]
                      city: "Updated City"
                      postalCode: "AB12 3CD"
                      country: "ENGLAND"
      responses:
        '200':
          description: Organization updated successfully
          headers:
            X-Correlation-ID:
              schema:
                type: string
                example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
              description: 'The X-Correlation-ID from the request header, if supplied, mirrored back.'
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
            X-XSS-Protection:
              description: Enable XSS filtering
              schema:
                type: string
                example: "1; mode=block"
            Strict-Transport-Security:
              description: Enforce HTTPS
              schema:
                type: string
                example: "max-age=31536000; includeSubDomains"
            ETag:
              description: Version identifier for the resource
              schema:
                type: string
                example: "W/\"2\""
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                updated_organization:
                  summary: Updated Organization Response
                  value:
                    resourceType: Organization
                    id: "00000000-0000-0000-0000-00000000000a"
                    meta:
                      profile: ["https://fhir.nhs.uk/StructureDefinition/UKCore-Organization"]
                      versionId: "2"
                      lastUpdated: "2024-01-15T11:30:00.000Z"
                    active: true
                    name: "Updated GP Practice Name"
                    type:
                      - coding:
                          - system: "https://fhir.hl7.org.uk/CodeSystem/UKCore-OrganizationType"
                            code: "GP"
                            display: "GP Practice"
                    identifier:
                      - system: "https://fhir.nhs.uk/Id/ods-organization-code"
                        value: "ABC123"
                    telecom:
                      - system: phone
                        value: "01234 567890"
                        use: work
                    address:
                      - line: ["Updated Medical Practice", "Updated Street"]
                        city: "Updated City"
                        postalCode: "AB12 3CD"
                        country: "ENGLAND"
        '400':
          description: Bad Request - Invalid input data
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '401':
          description: Unauthorized - Invalid or missing API key
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '403':
          description: Forbidden - Access denied
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '404':
          description: Not Found - Organization does not exist
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '412':
          description: Precondition Failed - Version mismatch
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '422':
          description: Unprocessable Entity - Semantic validation errors
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '429':
          description: Too Many Requests - Rate limit exceeded
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
            Retry-After:
              description: Number of seconds to wait before retrying
              schema:
                type: integer
                example: 60
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
        '500':
          description: Internal Server Error
          headers:
            X-Content-Type-Options:
              description: Prevent MIME type sniffing
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              description: Prevent clickjacking attacks
              schema:
                type: string
                example: DENY
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
components:
  schemas:
    Organization:
      type: object
      required:
        - resourceType
        - id
        - meta
        - active
        - name
        - type
        - identifier
        - telecom
        - address
      properties:
        resourceType:
          type: string
          enum: [Organization]
          example: Organization
        id:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
          example: "00000000-0000-0000-0000-00000000000a"
          description: Unique identifier for the Organization resource
        meta:
          type: object
          required:
            - profile
          properties:
            profile:
              type: array
              items:
                type: string
                pattern: "^https://fhir\\.nhs\\.uk/StructureDefinition/.*"
              example: ["https://fhir.nhs.uk/StructureDefinition/UKCore-Organization"]
              minItems: 1
            versionId:
              type: string
              example: "1"
              description: Version of the resource
            lastUpdated:
              type: string
              format: date-time
              example: "2024-01-15T10:30:00.000Z"
              description: When the resource was last updated
        active:
          type: boolean
          example: true
          description: Whether the organization is active
        name:
          type: string
          minLength: 1
          maxLength: 255
          pattern: "^[\\s\\S]*\\S[\\s\\S]*$"
          example: "GP Practice Name"
          description: Name of the organization
        type:
          type: array
          items:
            type: object
            required:
              - coding
            properties:
              coding:
                type: array
                items:
                  type: object
                  required:
                    - system
                    - code
                  properties:
                    system:
                      type: string
                      format: uri
                      pattern: "^https://.*"
                      example: "https://fhir.hl7.org.uk/CodeSystem/UKCore-OrganizationType"
                      description: Code system URI
                    code:
                      type: string
                      minLength: 1
                      example: "GP"
                      description: Organization type code
                    display:
                      type: string
                      example: "GP Practice"
                      description: Human readable description of the code
          minItems: 1
          description: Type of organization
        identifier:
          type: array
          items:
            type: object
            required:
              - system
              - value
            properties:
              system:
                type: string
                enum: [https://fhir.nhs.uk/Id/ods-organization-code]
                example: https://fhir.nhs.uk/Id/ods-organization-code
                description: Identifier system URI
              value:
                type: string
                pattern: "^[A-Z0-9]{1,12}$"
                example: ABC123
                description: ODS organization code
          minItems: 1
          description: Organization identifiers
        telecom:
          type: array
          items:
            type: object
            required:
              - system
              - value
            properties:
              system:
                type: string
                enum: [phone, email, fax, url]
                example: phone
                description: Type of contact
              value:
                type: string
                minLength: 1
                example: "01234 567890"
                description: Contact value
              use:
                type: string
                enum: [home, work, temp, old, mobile]
                example: work
                description: Purpose of the contact
          minItems: 1
          description: Contact information
        address:
          type: array
          items:
            type: object
            required:
              - line
              - city
              - postalCode
              - country
            properties:
              line:
                type: array
                items:
                  type: string
                  minLength: 1
                example: ["Example Medical Practice", "Example Street"]
                minItems: 1
                maxItems: 5
                description: Street address lines
              city:
                type: string
                minLength: 1
                maxLength: 100
                example: "Example City"
                description: City name
              postalCode:
                type: string
                pattern: "^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$"
                example: "AB12 3CD"
                description: UK postal code
              country:
                type: string
                enum: ["ENGLAND", "SCOTLAND", "WALES", "NORTHERN IRELAND"]
                example: "ENGLAND"
                description: Country name
          minItems: 1
          description: Organization addresses
    OperationOutcome:
      type: object
      required:
        - resourceType
        - issue
      properties:
        resourceType:
          type: string
          enum: [OperationOutcome]
          example: OperationOutcome
        id:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
          example: 6f4ca309-19d7-4f61-90b3-acbd1f2eb8f8
          description: Unique identifier for the operation outcome
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                type: string
                pattern: "^https://.*"
              example: ["https://simplifier.net/guide/UKCoreDevelopment2/ProfileUKCore-OperationOutcome"]
              minItems: 1
            versionId:
              type: string
              example: "1"
            lastUpdated:
              type: string
              format: date-time
              example: "2024-01-15T10:30:00.000Z"
        issue:
          type: array
          items:
            type: object
            required:
              - severity
              - code
            properties:
              severity:
                type: string
                enum: [fatal, error, warning, information]
                example: error
                description: Severity of the issue
              code:
                type: string
                enum: [invalid, structure, required, value, invariant, security, login, unknown, expired, forbidden, suppressed, processing, not-supported, duplicate, multiple-matches, not-found, too-long, code-invalid, extension, too-costly, business-rule, conflict, transient, lock-error, no-store, exception, timeout, incomplete, throttled, informational]
                example: invalid
                description: Type of issue
              details:
                type: object
                properties:
                  coding:
                    type: array
                    items:
                      type: object
                      required:
                        - system
                        - code
                      properties:
                        system:
                          type: string
                          format: uri
                          pattern: "^https://.*"
                          example: https://fhir.nhs.uk/Codesystem/http-error-codes
                          description: Code system URI
                        code:
                          type: string
                          minLength: 1
                          example: INVALID
                          description: Error code
                        display:
                          type: string
                          example: "Invalid input"
                          description: Human readable error description
                  text:
                    type: string
                    example: "The provided data is invalid"
                    description: Plain text description of the issue
              diagnostics:
                type: string
                minLength: 1
                maxLength: 1000
                example: 'Invalid resource.'
                description: Additional diagnostic information
              location:
                type: array
                items:
                  type: string
                example: ["Organization.name"]
                description: Path to the element that caused the issue
              expression:
                type: array
                items:
                  type: string
                example: ["Organization.name"]
                description: FHIRPath expression identifying the issue location
          minItems: 1
          description: List of issues found
  securitySchemes:
    app-level0:
      type: apiKey
      in: header
      name: apiKey
      description: |
        API key authentication. The API key must be provided in the 'apiKey' header.
        API keys are issued during the onboarding process and must be kept secure.

        Security considerations:
        - API keys should be rotated regularly
        - Keys should be stored securely and not logged
        - Keys should not be embedded in client-side code
        - Use HTTPS for all API communications
        - Implement rate limiting and monitoring
x-nhsd-apim:
  target:
    $ref: x-nhsd-apim/target.yaml
  access:
    - title: Application-restricted with API key
      grants:
        app-level0: []
